default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: videoencoder

test:
  <<: *default
  database: videoencoder_test

production:
  <<: *default
  database: videoencoder
  username: root
  password: <%= ENV['VIDEOENCODER_MYSQL_PASSWORD'] %>