default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: videoencoder
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: videoencoder_test

production:
  <<: *default
  url: <%= ENV['VIDEOENCODER_MYSQL_URL'] %>
  socket: /var/run/mysqld/mysqld.sock